# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 🚀 🔨 Subir no servidor FTP de Produção
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: 🚀 🔨 Subir no servidor FTP de Produção
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtenha o código mais recente do github
      uses: actions/checkout@v2

    - name: ☁️ Sincronizar arquivos no servidor FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ vars.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**